with audits_id as (
    update address_level set is_voided = true
        where title not in ('Payari',
                            'Tarang',
                            'Katurdona',
                            'Khalebhanvar',
                            'Khamroud Village',
                            'Tankitola',
                            'Chatua (Anuppur)',
                            'Piparaha (Near Chaura Dadar)',
                            'Tarera',
                            'Sital pani',
                            'Sarai (Near Tarang)',
                            'Mithu mahua',
                            'Tithi',
                            'Jaithari',
                            'Dona',
                            'Daldali',
                            'Khumni',
                            'BulhuPani',
                            'Dadra Silvari',
                            'Neeche Silvari',
                            'Kodar Village',
                            'Sarfa',
                            'Khirni',
                            'Ahirgawan',
                            'Badi Tumi',
                            'Thunguni',
                            'Duradhar',
                            'Kharsol',
                            'Chirpani',
                            'Dabhaniya',
                            'Majhauli',
                            'Kui',
                            'Padmania Village',
                            'Gijri',
                            'Amoda',
                            'Batiya',
                            'Bijora',
                            'Khosurgod',
                            'Bairagi',
                            'Alwar Village',
                            'Adwar',
                            'Lamsarai (Near Keshwani)',
                            'Lamsarai (Near Ahirwar)',
                            'Ghata',
                            'Hathbandha',
                            'Karoundi',
                            'Salar Gondi',
                            'Sarai Paterra',
                            'Udal',
                            'Bijapuri No.2',
                            'Debridadar',
                            'Bhuratola',
                            'Bartola',
                            'Uprikhurd',
                            'Bicharpur',
                            'Manjhetola',
                            'Ledhra',
                            'Picharwahi',
                            'Jarwahi',
                            'Dudhmania',
                            'Padri (near Chaura Dadar)',
                            'Bakantola',
                            'Ghurritola',
                            'Jairhi',
                            'Harradadar',
                            'Konhatola',
                            'Doomartola',
                            'Navatola',
                            'Pakripani',
                            'Pakhatola',
                            'Belapani',
                            'Ufrikala',
                            'Karaunda Pani'
            )
            and type_id = 5
            and address_level.type_id = 5 returning audit_id)
update audit
set last_modified_date_time=current_timestamp
where id in (select audit_id from audits_id);
